Repository swiftwasm/WasmTransformer, pull requests merged in 2020-10, with the labels that each got.

#8 Add a LICENSE file
  LICENSE
Labels: documentation

#9 Fix release mode bug and improve performance
  Sources/WasmTransformer/BinaryFormat.swift
  Sources/WasmTransformer/I64Transformer.swift
  Sources/WasmTransformer/InputStream.swift
Labels: bug, enhancement

#7 Run unit tests on Ubuntu
  .github/workflows/test.yml
  Sources/WasmTransformer/I64Transformer.swift
  Tests/WasmTransformerTests/IntegrationTests.swift
Labels: enhancement
